"""add service_id

Revision ID: 4fb17f625a7
Revises: 47d650971d
Create Date: 2015-06-23 22:59:49.052970

"""

# revision identifiers, used by Alembic.
revision = '4fb17f625a7'
down_revision = '47d650971d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('service_id', sa.Unicode(), nullable=True))
    op.add_column('persons', sa.Column('service_id', sa.Unicode(), nullable=True))
    op.add_column('songs', sa.Column('service_id', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'service_id')
    op.drop_column('persons', 'service_id')
    op.drop_column('albums', 'service_id')
    ### end Alembic commands ###
